---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
# For some reason, kibana is unaccessible if this next line is commented out.
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200